# Default values for generic.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image: $CLIENT_INT_IMAGE

imagePullPolicy: IfNotPresent

command: ["python3"]
#command: ["node"]
#command: ["lua"]
#command: ["R"]
#command: ["java"]

nameOverride: ""
fullnameOverride: ""

clientApp:
  name: client-app

useSGXDevPlugin: disabled

scone:
  las: 172.17.0.1:18766
  cas: $SCONE_CAS_ADDR
  configID: $SESSION/client-app

securityContext:
  privileged: true
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  containerPort: 8080
  port: 80

extraEnvVars:
  - name: SCONE_VERSION
    value: "1"
  - name: SCONE_HEAP
    value: "256M"
  - name: SCONE_ALLOW_DLOPEN
    value: "2"

extraSGXVolumes:
  name: dev-isgx
  hostPath: $DEVICE

extraSGXVolumeMounts:
  name: dev-isgx
  path: $DEVICE

extraClientAppRepoVolumes:
  name: genesis
  hostPath: /host

extraClientAppRepoVolumeMounts:
  name: genesis
  path: /home/client-app

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
