apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.clientApp.name }}
  labels:
    app: {{ .Values.clientApp.name }}
    group: {{ .Values.clientApp.name }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: port1
      protocol: TCP
      name: port1
  selector: {{- include "generic.selectorLabels" . | nindent 4 }}
