{{- if not .Values.useSGXDevPlugin }}
{{- required "A valid '.Values.useSGXDevPlugin' is required: \"enabled\"|\"scone\"|\"azure\"|\"disabled\"" .value }}
{{- else if and (ne .Values.useSGXDevPlugin "enabled") (ne .Values.useSGXDevPlugin "scone") (ne .Values.useSGXDevPlugin "azure") (ne .Values.useSGXDevPlugin "disabled") }}
{{- required "A valid '.Values.useSGXDevPlugin' is required: \"enabled\"|\"scone\"|\"azure\"|\"disabled\"" .value }}
{{- end }}

apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "las.fullname" . }}
  labels:
    {{- include "las.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "las.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "las.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      volumes:
        {{- if eq .Values.useSGXDevPlugin "disabled" }}
        - hostPath:
            path: /dev/isgx
          name: dev-isgx
        {{- end }}
      containers:
        - name: las
          image: "{{ .Values.image }}"
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          securityContext:
          {{- if eq .Values.useSGXDevPlugin "enabled" }}
            capabilities:
              add: ["SYS_RAWIO"]
          {{- else }}
            privileged: true
          {{- end}}
          tty: true
          ports:
          - containerPort: 18766
            name: attestation
            protocol: TCP
            {{- if .Values.service.hostPort }}
            hostPort: 18766
            {{- end }}
          {{- if or (.Values.resources) (eq .Values.useSGXDevPlugin "enabled") }}
          resources:
          {{- if .Values.resources }}
          {{- toYaml .Values.resources | nindent 12 }}
          {{- end }}
          {{- if eq .Values.useSGXDevPlugin "enabled" }}
            limits:
              sgx.k8s.io/sgx: 1
          {{- else if eq .Values.useSGXDevPlugin "azure" }}
          {{- end}}
          {{- end}}
          volumeMounts:
                      {{- if eq .Values.useSGXDevPlugin "disabled" }}
            - name: dev-isgx
              mountPath: /dev/isgx
            {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
