apiVersion: v2
description: Deploy SCONE LAS to Kubernetes
home: https://scontain.com/
icon: https://scontain.com/img/logo-vector-black-text.svg
maintainers:
- email: info@scontain.com
  name: Clenimar
name: las
type: application
version: 0.3.1
